trigger:
  - main

pool:
  name: Default  # Uses your self-hosted agent

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: echo "Installing dependencies..."
            displayName: 'Install dependencies (mock)'

          - script: echo "Build successful!"
            displayName: 'Run build (mock)'

          - script: |
              echo "Running tests..."
              echo "Tests passed!"
            displayName: 'Run tests (mock)'
