trigger:
  - main

pool:
  name: Default  # Use your self-hosted agent pool

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
            displayName: 'Install dependencies'

          - script: |
              echo "Build successful!"
            displayName: 'Run build (placeholder)'

          - script: |
              echo "Running tests..."
              echo "Tests passed!"
            displayName: 'Run tests (placeholder)'
